name: The main workflow
on: push

jobs:
  build:
    name: The build job
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo does this work when merging a pull request?

      - id: test
        run: false

      - name: if steps.test.outcome == 'failure'
        if: steps.test.outcome == 'failure'
        run: echo "this does not run"

      - name: if failure() && steps.test.outcome == 'failure'
        if: failure() && steps.test.outcome == 'failure'
        run: echo "this runs"
