name: The main workflow
on: push

jobs:
  build:
    name: The build job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Step One
        id: one
        run: true
      - name: Step Two
        id: two
        run: false
      - name: if steps.id.outcome == failure
        if: steps.two.outcome == 'failure'
        run: echo oops
      - name: if failure()
        if: failure()
        run: echo ${{ steps.two.outcome }}
