name: The main workflow
on: push

jobs:
  build:
    name: The build job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./action-a
        env:
          MY_NAME: "John"
