name: The main workflow
on: push

jobs:
  build:
    name: The build job
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }} to ${{ github.ref }}

      - id: test
        run: false

      - name: if steps.test.outcome == 'failure'
        if: steps.test.outcome == 'failure'
        run: echo "this does not run"

      - name: if failure() && steps.test.outcome == 'failure'
        if: failure() && steps.test.outcome == 'failure'
        run: echo "this runs"
